services:
  db:
    image: postgres:15
    container_name: car_loan_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_loan
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
