# Generated by Django 5.2 on 2025-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'available'), ('loaned', 'loaned'), ('maintenance', 'maintenance')], default='available', max_length=20)),
            ],
        ),
    ]
