# Generated by Django 5.2 on 2025-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_vehicle_status_vehiclerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='active', max_length=10),
        ),
    ]
